name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: alphahinex/hf-models:test

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 32768
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
    - name: Check
      run: |
        echo "Free space:"
        df -h
    - uses: actions/checkout@v3
    - name: create TONEK_FILE
      run: echo ${{ secrets.HF_TOKEN }} > TONEK_FILE
    - name: Build the Docker image
      run: |
        cat /etc/docker/daemon.json
        ps -ef|grep dockerd
        docker build . --file Dockerfile --tag $IMAGE_NAME
    - name: clean TONEK_FILE
      run: rm -f TONEK_FILE

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image
      run: docker push $IMAGE_NAME
