name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: alphahinex/hf-models:main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 5120
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
    - name: Check
      run: |
        echo "Free space:"
        df -h
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HUGGINGFACE_HUB_CACHE: /home/runner/work/hf-models/hf-models
      run: docker build . --file Dockerfile --tag $IMAGE_NAME

    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image
      run: docker push $IMAGE_NAME